export const defaultStats = {
    games_played: "?",
    season: "?",
    min: "?",
    fgm: "?",
    fga: "?",
    fg3m: "?",
    fg3a: "?",
    ftm: "?",
    fta: "?",
    oreb: "?",
    dreb: "?",
    reb: "?",
    ast: "?",
    stl: "?",
    blk: "?",
    turnover: "?",
    pf: "?",
    pts: "?",
    fg_pct: "?",
    fg3_pct: "?",
    ft_pct: "?",
}

export const defaultPlayer = {
    id: "default",
    first_name: "?",
    height_feet: "?",
    height_inches: "?",
    last_name: "?",
    position: "?",
    team: {
        id: "?",
        abbreviation: "?",
        city: "?",
        conference: "?",
        division: "?",
        full_name: "?",
        name: "?"
    },
    weight_pounds: "?",
    number: "?",
    photo: "https://www.rapidpackaging.com/wp-content/uploads/2018/06/person-placeholder-300x200.jpg",
}
